algoritmo "Carteira_motorista"
// Função :  base na idade e se a mesma é habilitada, dizer como Verdadeiro ou Falso se ela pode dirigir.
// Autor : Maria Eduarda Batista de Oliveira
// Data : 21/06/2022
// Seção de Declarações 
var
 idad: real
 habilit: logico
inicio
// Seção de Comandos 
//entrada
escreval("Qual a sua idade?")
leia (idad)
//processamento
habilit <- (idad>=18) xou (habilit=nao)
fimalgoritmo
