Algoritmo "mediade3numeros"
// Professor   : Cintia Pinho
// Descrição   : calcular a media de 3 numeros
// Autor(a)    : Maria Eduarda
// Data atual  : 08/03/2022
Var
n1,n2,n3,media:real


Inicio
//entrada
escreval ("escreva o primeiro numero")
leia (n1)
escreval ("escreva o segundo numero")
leia (n2)
escreval ("escreva o terceiro numero")
leia (n3)

//processamento
media <- (n1+n2+n3)

//saida
 escreval ("A media dos tres numeros é:",media)

Fimalgoritmo