algoritmo "Calculopeca"
// Função : Solicitar o valor da peça, quantidade comprada e total da compra
// Autor : Maria Eduarda
// Data : 26/04/2022
// Seção de Declarações 
var
valor,qnt,total:real
inicio
//entrada
escreval("digite a quantidade de peças compradas")
leia(qnt)
escreval("Digite o valor unitário de cada peça")
leia(valor)
//processamento
total<-valor*qnt

//saida
escreval("O valor total da sua compra é:",total)
// Seção de Comandos 

fimalgoritmo
