  Algoritmo ""
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você soma números aleatórios
// Autor(a)    : Maria Eduarda Batista de Oliveira
// Data atual  : 29/08/2022
Var
acu,num: inteiro


Inicio
escreval("PARA ENCERRAR, DIGITE 0")
repita
escreval("Digite um número")
leia(num)
acu <- acu+num
escreval("SOMANDO...", acu)
ate (num=0)
interrompa



Fimalgoritmo