Algoritmo "Exercicio_3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Gera  e escreve os números ímpares entre 100 e 200
// Autor(a)    : Maria Eduarda Batista De Oliveira
// Data atual  : 06/09/2022
Var
cont: inteiro
inicio
cont <- 100
enquanto cont < 200 faca
se cont mod 2=1 entao
escreval (cont)
fimse
cont <- cont +1
fimenquanto
fimalgoritmo
